
proxies:
  http: ${{ secrets.PROXY }}
  https: ${{ secrets.PROXY }}

db_url: ${{ secrets.REMOTE_DB }}

workers: $WORKERS

data_scrappers:
  - name: lyricsmint
    path: scrapper.data.lyricsmint_scrapper
    class: LyricsMintDataScrapper

link_scrappers:
  - name: lyricsmint
    path: scrapper.link.lyricsmint_scrapper
    class: LyricsMintLinkScrapper