workers: 100

data_scrappers:
  - name: lyricsmint
    path: scrapper.data.lyricsmint_scrapper
    class: LyricsMintDataScrapper

link_scrappers:
  - name: lyricsmint
    path: scrapper.link.lyricsmint_scrapper
    class: LyricsMintLinkScrapper