workers: 100

data_scrappers:
  - name: lyricsmint
    path: scrapper.data.lyricsmint_scrapper
    class: LyricsMintDataScrapper

  - name: ilyrichub
    path: scrapper.data.ilyrichub_scrapper  
    class: ILyricHubDataScrapper

link_scrappers:
  - name: lyricsmint
    path: scrapper.link.lyricsmint_scrapper
    class: LyricsMintLinkScrapper
    page: 10

  - name: ilyrichub
    path: scrapper.link.ilyrichub_scrapper
    class: ILyricHubLinkScrapper
    page: 10