data_scrappers:
  - name: lyricmint
    path: scrappers.data.lyricmint_scrapper
    class: LyricMintDataScrapper


link_scrappers:
  - name: lyricmint
    path: scrappers.link.lyricmint_scrapper
    class: LyricMintLinkScrapper