services:
  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=ankit
      - MYSQL_PASSWORD=ankit
      - MYSQL_DATABASE=songdb